package photon

const (
	typeUnknown          = byte(0)
	typeBoolean          = byte(2)
	typeByte             = byte(3)
	typeShort            = byte(4)
	typeFloat            = byte(5)
	typeDouble           = byte(6)
	typeString           = byte(7)
	typeNull             = byte(8)
	typeCompressedInt    = byte(9)
	typeCompressedLong   = byte(10)
	typeInt1             = byte(11)
	typeInt1Neg          = byte(12)
	typeInt2             = byte(13)
	typeInt2Neg          = byte(14)
	typeLong1            = byte(15)
	typeLong1Neg         = byte(16)
	typeLong2            = byte(17)
	typeLong2Neg         = byte(18)
	typeCustom           = byte(19)
	typeDictionary       = byte(20)
	typeHashtable        = byte(21)
	typeObjectArray      = byte(23)
	typeOperationRequest = byte(24)
	typeOperationResp    = byte(25)
	typeEventData        = byte(26)
	typeBoolFalse        = byte(27)
	typeBoolTrue         = byte(28)
	typeShortZero        = byte(29)
	typeIntZero          = byte(30)
	typeLongZero         = byte(31)
	typeFloatZero        = byte(32)
	typeDoubleZero       = byte(33)
	typeByteZero         = byte(34)
	typeArray            = byte(0x40)
	customTypeSlimBase   = byte(0x80)
)

const maxArraySize = 65536
